project:
  type: book

book:
  title: "Documento base"
  author: "Pablo Álvarez Arnedo"
  date: "26/11/2024"
  chapters:
    - index.qmd
    - cap2.qmd
    - cap3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    # - custom.scss
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    toc-title: "Contenido"
    number-sections: false
editor: visual

