project:
  type: book

book:
  title: "Documento base"
  author: "Pablo Álvarez Arnedo"
  date: "26/11/2024"
  chapters:
    - index.qmd
    - cap2.qmd
    - cap3.qmd
    - cap4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    # - custom.scss
  pdf:
    documentclass: scrreprt
    toc-title: "Tabla de contenidos"
editor: visual

